### PR TITLE
v2

### PR DESCRIPTION
**Pull request by SuperK2-OS**

### CODE REVIEW

**Review by VuBrian22 — CHANGES_REQUESTED** [review]
It's fine the way it is. If you want to change the language than change it yourself but keep this repository's source in English.

**Review by SuperK2-OS — COMMENTED** [review]
Updated ?

**Comment by SuperK2-OS** [comment]
Sorry Im a github n00b

**Comment by VuBrian22** [comment]
If you want to make changes to the source, I'd recommend you removing your links to your site and discord. The dev if he chooses to merge this pull request will probably not tolerate self-promotion in his code.

**Comment by VuBrian22** [comment]
If you want to make and call the source "your own" and share it with your community then make a fork of the source and make changes to the code as you wish without needing to make a pull request to the original source.

**Comment by v3ctra** [comment]
Hey, 
The reposistory will be keept in English, you can modify source, share with community, create forks, but don't modify my repo with links to another sites. I won't accept it.

Have a nice day :)

**Pull request closed without merging**
